source: .
destination: ./_site
timezone: Europe/Rome
highlighter: pygments
paginate: 10
paginate_path: page/:num/
exclude:
  - bower.json
  - Gruntfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - static/less/
  - _site/
  - README.md
